### ISSUE TITLE
can't find resources when using pip to install

### ISSUE THREAD

**Issue by zhuque** [jackwluo/py-quantmod#2]
when I  use pip install quant, it remind me of "Could not find a version that satisfies the requirement quantmod (from versions: ) No matching distribution found for quantmod".

**Comment by FarshidHosseini** [comment]
Hi Jack,
I have the same issue as zhuque has. I run Python 3.6 but neither pip nor conda is able to install quantmod. Do I need to downgrade to an older version of Python?

**Comment by opalbert** [comment]
Hello Jack, I  pip install quantmod, didn't work for me on windows. Am I missing anything? I am using python 3.5 and I think it is the same issue as above.

**Comment by jackwluo** [comment]
Removed quantmod from pip temporarily. Currently working on version 2.0 where the library should be time-series agnostic, with drastic changes in both functionnality and syntax. In other words, I want a library where quantmod can plot any pandas timseries intuitively, not just OHLCV data of a very specific form (Yahoo currently). For now I would recommend simply dragging the quantmod folder inside py-quantmod to your project directory and using it locally

**Comment by adammarples** [comment]
Could you then remove "pip install quantmod" from the Readme?

**Comment by Jignesh-git** [comment]
Hi jackluo,

any update on release of version 2.0. We are eagerly waiting for updates.

**Comment by ravichawla** [comment]
Any update in 2020?

**Comment by bigdatafran** [comment]
in 2023 there is an update?. Now there are many conflicts with other packages
