### ISSUE TITLE
RSI MACD not working for many stock tickers

### ISSUE THREAD

**Issue by zhang01GA** [jackwluo/py-quantmod#3]
Try stock tickers: SUN.AX,  IAG.AX, WES. AX. Their price can be displayed. But the TA indices cutoff in the middle of the datetime axis. Must be a bug.

**Comment by jackwluo** [comment]
Fei, can you attach a screenshot so I can see the problem? Thanks

**Comment by zhang01GA** [comment]
Hi Jack. Thanks for the response. 
I figured out it is not bugs from your code. The root course is that yahoo historical prices had some missing segments in these stocks, particularly with SUN.AX in 2017.  If you just use SUN.AX,  WES.AX, as a ticker name, try to plot RSI, MACD etc. You will see incomplete plot lines.  
What do you reckon? how can we get yahoo to fix their historical prices?

**Comment by jackwluo** [comment]
Ah, the yahoo api is currently broken. For instance if you try to scrape,
the close and adjusted close columns are inverted. I'd suggest you use
Google or Quandl for now, all libraries are affected
